name: Jira PreDeployment setup Action
on:
  workflow_dispatch:
  

jobs:
  CloneAnsibleRepo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Ansible Repo
      uses: actions/checkout@v2
      with:
          repository: BalrajBemainboina/generalapp
          ref: master
          clean: false
  
  CurrentStateReport:
      runs-on: ubuntu-latest
      needs: [CloneAnsibleRepo]
      steps:
      - name: Generates Current State Report
        run: echo "Running Ansible Playbook for Current State report"
  
  TargetStateReport:
      runs-on: ubuntu-latest
      needs: [CloneAnsibleRepo, CurrentStateReport]
      steps:
      - name: Generates Target State Report
        run: echo "Running Ansible Playbook for Target State report"
