name: Jira PreDeployment setup Action
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Ticket Key'
        default: 'Test'
        required: true

jobs:
  CloneAnsibleRepo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout zip config
      uses: actions/checkout@v2
      with:
          repository: BalrajBemainboina/generalapp
          ref: master
          clean: false
